# Generated by Django 4.0.1 on 2022-02-08 18:53

from django.db import migrations, models
import embed_video.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sender', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('video_url', embed_video.fields.EmbedVideoField()),
                ('site_name', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
