# Generated by Django 4.0.1 on 2022-01-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='details',
            field=models.TextField(default='description goes in here'),
            preserve_default=False,
        ),
    ]
