# Generated by Django 4.0.1 on 2022-02-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='site_name',
            field=models.CharField(choices=[('Youtube', 'Youtube'), ('Vimeo', 'Vimeo')], max_length=50),
        ),
    ]
