# Generated by Django 4.0.1 on 2022-01-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_video_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
