# Generated by Django 4.0.1 on 2022-02-12 18:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_video_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
