# Generated by Django 4.0.1 on 2022-01-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_video_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sender', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
